Ctrl+DEL script-message playlist-remove current
Ctrl+BS script-message playlist-remove current
SHIFT+r cycle shuffle
Ctrl+o script-message open-dir

UP add video-zoom +0.1
DOWN add video-zoom -0.1

ctrl+RIGHT add video-pan-x -0.05
ctrl+LEFT add video-pan-x +0.05
ctrl+UP add video-pan-y +0.05
ctrl+DOWN add video-pan-y -0.05

# Copy current video file to working directory with "mpv-copy" prefix
S run sh -c 'cp -v "$1" "$PWD/mpv-copy-$(basename "$1")"' _ "${path}"

# Launch new mpv in the directory of the current file
n run sh -c 'cd "$(dirname "$1")" && setsid mpv --loop-playlist * &' _ "${path}"

# Launch new mpv recursively finding all video files in the directory
N run sh -c 'cd "$(dirname "$1")" && setsid find . -type f \( -iname "*.mp4" -o -iname "*.mkv" -o -iname "*.avi" -o -iname "*.mov" -o -iname "*.webm" -o -iname "*.flv" -o -iname "*.m4v" -o -iname "*.gif" -o -iname "*.ogv" -o -iname "*.mpg" -o -iname "*.mpeg" -o -iname "*.wmv" \) -exec mpv --loop-playlist {} +' _ "${path}"
